version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_dockerizing
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 240219
      POSTGRES_DATABASE: test_avito
      SERVER_ADDRESS: 8080
    volumes:
      - database_dockerizing:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - fullstack

  api:
    container_name: api_dockerizing
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=240219
      - POSTGRES_DATABASE=test_avito
      - SERVER_ADDRESS=8080
    depends_on:
      - postgres
    networks:
      - fullstack

volumes:
  database_dockerizing:
  api_volume:

networks:
  fullstack:
    driver: bridge
